### PR TITLE
Updates for image and title

### PR DESCRIPTION
**Pull request by rogerdc**

### CODE REVIEW

**Comment by xtaran** [comment]
Thanks. Was confused because you closed the first PR #1 nearly immediately again without comment. 

Do you happen to know if old images are still GIF, or have been converted to JPEG, too? I wonder if there should be a check if the JPEG exists and if not, fall back to GIF. Then again, probably nobody will make the script go back that far. So it should be ok.

I though strongly dislike the change from `alt="([^"]*)"` to `alt="(.*)"` in the second commit.  That doesn't make sense to me as it would catch any HTML attribute after the `alt` attribute. So the content would be something like e.g. `Non-Bonery 6" width="100%`. If the width parameter should be included, it should be matched separately. (Was that the intention? The commit messages is not very helpful in that regards.)

Similar arguments, albeit less severe, count for the switch of the regular expression to a less strict one in the first commit.

So I actually prefer your much cleaner first, now already closed pull request #1 over this one. So I have merged that one manually.

Feel free to discuss further changes with regards to `alt` and `width` attributes.

**Comment by rogerdc** [comment]
I fixed the file type, and submitted that pull request, but my fork wasn't getting the title--all of them were "Dummy". I've pulled yours again and run it here: 
```
                <item>
                        <title>"Dummy" - Mon, 19 Sep 2022</title>
                        <link>http://www.sinfest.net/view.php?date=2022-09-19</link>
                        <guid>http://www.sinfest.net/view.php?date=2022-09-19</guid>
                        <pubDate>Mon, 19 Sep 2022 00:00:00 -04:00</pubDate>
                        <description>&lt;img src="http://www.sinfest.net/btphp/comics/2022-09-19.jpg" border="0" alt="Dummy" /&gt;</description>
                </item>
```
What about changing the regex to `` character.

Running it with that regex looks like it fixes everything: 
```
                <item>
                        <title>"Non-Bonery 19" - Mon, 19 Sep 2022</title>
                        <link>http://www.sinfest.net/view.php?date=2022-09-19</link>
                        <guid>http://www.sinfest.net/view.php?date=2022-09-19</guid>
                        <pubDate>Mon, 19 Sep 2022 00:00:00 -04:00</pubDate>
                        <description>&lt;img src="http://www.sinfest.net/btphp/comics/2022-09-19.jpg" border="0" alt="Non-Bonery 19" /&gt;</description>
                </item>
```
What are your thoughts?

**Comment by rogerdc** [comment]
And OF COURSE I saw something else. All domains are now sinfest.xyz instead of sinfest.net.

**Comment by rogerdc** [comment]
I'll let you bump the version number, but here's what I've got now: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED BY Axel's Sinfest RSS Generator 0.02 -->
<rss version="0.92">
        <channel>
                <title>Sinfest</title>
                <link>http://www.sinfest.xyz</link>
                <description>Sinfest</description>
                <lastBuildDate>2022-09-19T13:57:23-0300</lastBuildDate>
                <copyright></copyright>
                <image>
                        <title>Sinfest</title>
                        <url>http://www.sinfest.xyz/rssicon.png</url>
                        <link>http://www.sinfest.xyz</link>
                        <width>28</width>
                        <height>30</height>
                </image>
                <item>
                        <title>"Non-Bonery 19" - Mon, 19 Sep 2022</title>
                        <link>http://www.sinfest.xyz/view.php?date=2022-09-19</link>
                        <guid>http://www.sinfest.xyz/view.php?date=2022-09-19</guid>
                        <pubDate>Mon, 19 Sep 2022 00:00:00 -04:00</pubDate>
                        <description>&lt;img src="http://www.sinfest.xyz/btphp/comics/2022-09-19.jpg" border="0" alt="Non-Bonery 19" /&gt;</description>
                </item>
                <item>
                        <title>"Non-Bonery 18" - Sun, 18 Sep 2022</title>
                        <link>http://www.sinfest.xyz/view.php?date=2022-09-18</link>
                        <guid>http://www.sinfest.xyz/view.php?date=2022-09-18</guid>
                        <pubDate>Sun, 18 Sep 2022 00:00:00 -04:00</pubDate>
                        <description>&lt;img src="http://www.sinfest.xyz/btphp/comics/2022-09-18.jpg" border="0" alt="Non-Bonery 18" /&gt;</description>
                </item>
[...]
        </channel>
</rss>
```

**Comment by rogerdc** [comment]
OK, there is no rssicon.png file anymore, so I just changed that to /favicon.ico. 

Last GIF is May 22, 2021. First JPG is May 23, 2021. 

What about changing the lines 98 and 99 to:
```
            if ($content =~ m{<img src="(btphp/comics/.*?\.(jpg|gif|png))" alt="(.*?)"}) {
                $img_url = $base_url . $1;
                $title = $3;
```
where `$base_url` is `https://www.sinfest.xyz`. 

I also switched all the URLs to https. 

I'm running a two-year retrieval now to make sure it's picking up the gif files in addition to the JPG.

**Comment by rogerdc** [comment]
There's some blocking issues with my VPN, but I'm now past the threshold of the gif files and it looks like it's working. I'll let it get back to September of 2020 (It's on April of 2021 now) and then commit and make another pull request.

**Pull request closed without merging**
